config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  get 'tags/:tag', to: 'posts#index', as: :tag
  devise_for :users
  resources :users, only: [:index,:edit, :update, :show, :new, :create]
  resources :posts, only: [:index,:new,:edit, :update,:create,:show,:destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
     collection do
    get 'search'
  end
end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_ancestry
  belongs_to :parent, class_name: :Category  
  has_many :children, class_name: :Category, foreign_key: :parent_id 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true  
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :saler, class_name: "User"
  belongs_to :buyer, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
 belongs_to :post, counter_cache: :likes_count
 belongs_to :post
 belongs_to :user

 validates :user_id, presence: true
 validates :post_id, presence: true
 validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :itemimag, ImageUploader

  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  validates :image, presence: true
  validates :itemimag, presence: true

  belongs_to :category
  validates :category_id, presence: true

  def self.search(search)
    if search
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
  acts_as_taggable
  def like_user(user_id)
    likes.find_by(user_id: user_id)
   end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true  
  
  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  mount_uploader :image_name, ImageUploader


  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text,:post_id,:user_id).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
   end

   def create
    　@item = Item.new(item_params)
    　if @item.save!
       item = Item.find(@item.id)
      #  redirect_to root_path
    　else
       redirect_to new_item_path
    　end
    end

    def item_params
      params.require(:item).permit(:name, :price, images: []) .merge(seller_id: current_user.id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    get_post
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    @like.destroy
    @likes = Like.where(post_id: params[:post_id])
    get_post
  end

  def get_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new 
    @post = Post.new
  end
  
  def create
    Post.create(post_params)
    @post = Post.new(post_params) 
    @post.user_id = current_user.id

  end

  def index
    @posts = Post.all
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(12)
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}")
    end
    @parents = Category.all.order("id ASC").limit(13)
    end

  def show
    @post = Post.find_by(id: params[:id])
    @text = @post.text
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
    @like = Like.new
  end
  
  def search
    @posts = Post.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(12)
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  private

 def post_params
  params.require(:post).permit(:text, :image, :tag_list, :clothesinfo, :name, :brand, :price, :itemimag, :category_id,).merge(user_id: current_user.id )
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(9)
    @introduce = @user.introduce
  end
  
  def index
    @mens = User.where(sex: '男性')
  end
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
    @user = User.find(params[:id])
   if @user.update(user_params)
  else
    render :edit
  end
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
  end

  def create
  end



  private
  def update_params
   params.require(:user).permit(:introduce,:age,:sex,:image_name)
  end

  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation, :image_name,:introduce,:age,:sex)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts/searches_helper.rb
module Posts::SearchesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/new.html.haml
.post
  = form_for(@item,local: true) do |f|
    .field
      .field-label
        = f.label :"服の種類"
      .field-input
        = f.text_field :name, placeholder: "例）Tシャツ"
    
    .field
      .field-label
        = f.label :"価格"
      .field-input
        = f.text_field :price

    .field
      .field-label
        = f.label :"画像"
      .field-input
        = f.file_field :image
   
    .actions
      = f.submit "出品する", class: 'btn'

app/views/likes/_like.html.haml
- if user_signed_in?
  - if post.like_user(current_user.id)
    .item-button-container__left__dislike
      =link_to post_like_path(current_user, post, like), method: "DELETE", remote: true do
        %i.fas.fa-heart
        %span いいね！
        %span 
          = post.likes_count
  - else
    .item-button-container__left__like
      =link_to  post_likes_path(current_user, post), method: "POST", remote: true do
        %i.fas.fa-heart
        %span いいね！
        %span
          = post.likes_count
-else
  .item-button-container__left__like
    %i.fas.fa-heart
      %span いいね！
    = post.like_count 

app/views/likes/create.js.haml
$(".item-button-container__left").html("#{escape_javascript(render partial: 'like', locals: { product: @post, posts: @posts, likes: @likes, like: @like})}")

app/views/posts/_header.html.haml
.header
  .header_contents
    .header_contents_btn_seach_form
      = form_tag( search_posts_path, method: :get )  do
        = text_field_tag :keyword, params[ :keyword], { placeholder: "投稿を検索する", class: "search-input" }
    .header_contents_btn_app_name
      = link_to "USED", root_path 
    .header_contents_btn_rigt_btn
      - if user_signed_in?
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_contents_btn_login_user" 
        = link_to current_user.name, user_path(current_user), class: "header_contents_btn_now_user"
      - else
        = link_to "ログイン", new_user_session_path, class: "header_contents_btn_login_user" 
        = link_to "新規登録", new_user_registration_path, class: "header_contents_btn_new_user" 

app/views/posts/_post.html.haml
.user_contents
  .main_contents_user_image
    = link_to post_path(post.id) do
      = image_tag post.image,:size =>'230x320'
  .main_contents_user_info
    .user_imag
      = link_to user_path(post.user.id) do
        = image_tag post.user.image_name, :size =>'40x40'
    .main_contents_user_name
      = link_to post.user.name, user_path(post.user.id)
    .main_contents_likes

app/views/posts/_tag.html.haml
.content_info_user_post_item
  - tag.each do |tag|
    = link_to tag, tag_path(tag_name: tag), class: "text-white"

app/views/posts/_top_main.html.haml
.main 
  .header
    = render partial: "header"
  .main_contents
    = render @posts
= paginate(@posts)

app/views/posts/create.html.haml
.contents 
  .success
    投稿が完了しました
    = link_to "マイページへ戻る", user_path(current_user)

app/views/posts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/edit.html.haml
.post
  = form_for(@post,local: true) do |f|
    .field
      .field-label
        = f.label :"画像"
      .field-input
        = f.file_field :image
    .field
      .field-label
        = f.label :"コーディネート詳細"
      .field-input
        = f.text_area :text, size: "45x5"
        
      .actions
      = f.submit "投稿する", class: 'btn'

app/views/posts/index.html.haml
.wrapper
  = render "top_main"

app/views/posts/new.html.haml
.post
  .header
    = render partial: "header"
  .post_form
    = form_for(@post,local: true) do |f|
      .post_name
        %h1
          ファッション投稿
      .field
        .field-label
          = f.label :"コーディネート画像"
          .item-num-0#image-box__container
        .field-input
          = f.label :image  do
            = icon('fas', 'image', class: 'messege_image fa-7x fa-spin')
            = f.file_field :image, class: 'input_box__image_file'
      .field
        .field-label
          = f.label :"コーディネート詳細"
        .field-input
          = f.text_area :text, size: "45x5",placeholder: "例)コーデ載せまーす( ^ω^ )皆さん元気ですか？私は元気ですよ( ´ ▽ ` )今日も張り切っていきましょう！！"
      .field
        .field-label
          = f.label :"カンマで区切ってタグをいっぱい書いてください" 
        .field-input
          = f.text_area :tag_list,size: "45x5",placeholder:"例）夏,海,コーデ,ストリートファッション"
      .post_name
        %h1
          商品出品
      .field
        .field-label
          = f.label :"商品画像"
          .item-num-0#image-box__container
        .field-input
          = f.label :itemimag  do
            = icon('fas', 'image', class: 'messege_image fa-7x fa-spin')
            = f.file_field :itemimag, class: 'input_box__image_file'
      .field
        .field-label
          = f.label :"商品名"
        .field-input
          = f.text_field :name, class: 'used__name', placeholder: ' 40文字まで',size: "45x5"
      .field
        .field-label
          = f.label :"商品の詳細"
        .field-input
          = f.text_area :clothesinfo, size: "45x5"
      .field
        .field-label
          = f.label :"ブランド"
        .field-input
          = f.text_field :brand, class: 'used__name', placeholder: ' apple',size: "45x5"
      .field
        .field-label
          = f.label :"価格"
        .field-input
          = f.number_field  :price, class: 'used__name', placeholder: ' 1000'
          円
      .actions
      = f.submit "投稿する", class: 'btn'

app/views/posts/search.html.haml
.header
  = render partial: "header"
.searches
  - @posts.each do |post|
    = render partial: "post", locals: { post: post }

app/views/posts/show.html.haml
.content
  .header
    = render partial: "header"
  .user_header
    .user_imag
      = link_to user_path(@post.user.id) do
        = image_tag @post.user.image_name, :size =>'70x70'
    .user_header_name
      = @post.user.name
    - if user_signed_in? && current_user.id == @post.user_id
      .user_post_edit
        = link_to edit_post_path(@post.id), method: :get do
          = icon('fa', 'edit', class: "user_name__btn--icon")
      .user_post_delet
        = link_to "/posts/#{@post.id}", method: :delete do
          = icon('fa', 'trash-alt' , class: "user_name__btn--icon")
      .like-button
        = render partial: "likes/like", locals: { post: @post, posts: @posts, likes: @likes, like: @like}
  .content_info
    .content_info_user_post
      .content_info_user_post_content
        .content_info_user_post_image
          = image_tag @post.image
        .content_info_user_post_text
          .format
            %a コーディネートの内容
          .content_info_user_post_text_comment
            = simple_format(@text)
            .content_info_user_post_tag
              - @post.tag_list.each do |tag|
                %span{class: "content_info_user_post_tags"}= tag
      .product_fild
        %h1 出品商品
        .product_fild_name
          %h2 
            = @post.name
        .product_fild_text
          %h3
            = simple_format(@post.clothesinfo)
        .product_fild_info
          .product_fild_info_image
            = image_tag @post.itemimag
          .product_fild_info_detil
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    = @post.user.name
                %tr
                  %th
                    カテゴリー
                  %td
                    = @post.category.parent.parent.name
                    %br/
                    = @post.category.parent.name
                    %br/
                    = @post.category.name
                %tr
                  %th
                    ブランド
                  %td
                    = @post.brand
                %tr
                  %th
                    商品のサイズ
                  %td
                    M
                %tr
                  %th
                    価格
                  %td
                    = @post.price
                    円
        .product_fild_sell
          - if user_signed_in? && current_user.id == @post.user_id
            .product_fild_sell_delete
              = link_to "/posts/#{@post.id}", method: :delete, class:"product_delete" do
                %p 投稿の削除
          - else 
            .product_fild_sell_buy
              = link_to('', {}) do
                %p 商品の購入
      .comment_fild
        .content_info_user_post_comment_fild
          -if current_user
            = form_for [@post, @comment] do |f|
              .field
                .field-label 
                .field-input
                  = f.text_area :text,size: "100x5", placeholder: "コメントする",class:"comment_fild_form"
                .actions
                  = f.submit "コメントする", class: 'btn'
        .content_info_user_post_comment_list
          <コメント一覧>
        .comment_box
          - @comments.each do |comment|
            .comments_user_name
              = link_to comment.user.name, user_path(comment.user_id)
                
            .comment_title
              = comment.text

app/views/posts/update.html.haml
.contents 
  .success
    投稿が完了しました
    = link_to "マイページへ戻る", user_path(current_user)

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 プロフィール変更
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "マイページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(@user,multipart: true) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :"自己紹介"
          .field-input
            = f.text_area :introduce, size: "45x5"
        
        .field
          .field-label
            = f.label :age, '年齢', class:'control-label'
            = f.select :age, [["",""], ["10代","10"], ["20代","20"], ["30代","30"], ["40代","40"], ["50代","50"], ["60代","60"], ["70代以上","70"] ], {},   class: 'form-control'

        .field
          .field-label
            = f.label :"sex"
            = f.select :sex, [["",""], ["女性","女性"], ["男性","男性"]], {},   class: 'form-control'
        .field
          .field-label
            = f.label :"プロフィール画像"
          .field-input
            = f.file_field :image_name 
            
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.my_main
  .header
    = render partial: "posts/header"
  .my_main_title
    .user_header
      .user_sub
        .user_imag
          = image_tag @user.image_name, :size =>'150x150'
        .user_edit_btn
          - if current_user == @user
            = link_to "プロフィール変更", edit_user_path(current_user) 
          - else 
            .user_dm
              メッセージを送る
      .user_main
        .user_name
          = @name 
        .user_profle
          = simple_format(@introduce)
        .user_url
          -# = link_to @users[:id][:url]
  .main_content
    .main_content_box
      .main_content_box_post
        - if current_user == @user
          = link_to "コーディネート投稿", new_post_path, class:"main_content_box_post"
        - else 
          = "ユーザー投稿一覧"
      .main_content_box_list
        = render @posts